/**
 * Windows Terminal Adapter
 *
 * Integrates retro skins with Windows Terminal.
 * Windows Terminal uses JSON configuration files (settings.json).
 */

import type { SkinConfig } from '../../skins.js';

export interface WindowsTerminalConfig {
  /** Windows Terminal settings.json path */
  configPath: string;
  /** Whether to auto-save backup */
  backupEnabled: boolean;
}

export interface WindowsTerminalColorScheme {
  name: string;
  background: string;
  foreground: string;
  selectionBackground: string;
  cursorColor: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

/**
 * Convert our skin config to Windows Terminal format
 */
export function toWindowsTerminalColors(skin: SkinConfig): WindowsTerminalColorScheme {
  // Use custom palette if provided
  if (skin.colors.palette) {
    const p = skin.colors.palette;
    return {
      name: skin.name.replace(/\s+/g, ''),
      background: skin.colors.background,
      foreground: skin.colors.foreground,
      selectionBackground: skin.colors.accent,
      cursorColor: skin.colors.accent,
      black: p.black,
      red: p.red,
      green: p.green,
      yellow: p.yellow,
      blue: p.blue,
      magenta: p.purple,
      cyan: p.cyan,
      white: p.white,
      brightBlack: p.brightBlack,
      brightRed: p.brightRed,
      brightGreen: p.brightGreen,
      brightYellow: p.brightYellow,
      brightBlue: p.brightBlue,
      brightMagenta: p.brightPurple,
      brightCyan: p.brightCyan,
      brightWhite: p.brightWhite,
    };
  }

  // Auto-generate palette from base colors
  return {
    name: skin.name.replace(/\s+/g, ''),
    background: skin.colors.background,
    foreground: skin.colors.foreground,
    selectionBackground: skin.colors.accent + '80',
    cursorColor: skin.colors.accent,
    black: skin.colors.background,
    red: '#FF0000',
    green: '#00FF00',
    yellow: '#FFFF00',
    blue: '#0000FF',
    magenta: '#FF00FF',
    cyan: '#00FFFF',
    white: skin.colors.foreground,
    brightBlack: '#404040',
    brightRed: '#FF6666',
    brightGreen: '#66FF66',
    brightYellow: '#FFFF66',
    brightBlue: '#6666FF',
    brightMagenta: '#FF66FF',
    brightCyan: '#66FFFF',
    brightWhite: '#FFFFFF',
  };
}

/**
 * Generate Windows Terminal JSON configuration for a skin
 */
export function generateWindowsTerminalJson(skin: SkinConfig, options: Partial<WindowsTerminalConfig> = {}): string {
  const colors = toWindowsTerminalColors(skin);
  const config = {
    configPath: options.configPath || '%LOCALAPPDATA%/Packages/Microsoft.WindowsTerminal_8wekyb9d8bbwe/LocalState/settings.json',
    backupEnabled: options.backupEnabled ?? true,
  };

  return `// Retro Skin: ${skin.name}
// Generated by Retro Skins Platform

{
  "$schema": "https://aka.ms/terminal-profiles-schema",
  "schemes": [
    {
      "name": "${colors.name}",
      "background": "${colors.background}",
      "foreground": "${colors.foreground}",
      "selectionBackground": "${colors.selectionBackground}",
      "cursorColor": "${colors.cursorColor}",
      "black": "${colors.black}",
      "red": "${colors.red}",
      "green": "${colors.green}",
      "yellow": "${colors.yellow}",
      "blue": "${colors.blue}",
      "purple": "${colors.magenta}",
      "cyan": "${colors.cyan}",
      "white": "${colors.white}",
      "brightBlack": "${colors.brightBlack}",
      "brightRed": "${colors.brightRed}",
      "brightGreen": "${colors.brightGreen}",
      "brightYellow": "${colors.brightYellow}",
      "brightBlue": "${colors.brightBlue}",
      "brightPurple": "${colors.brightMagenta}",
      "brightCyan": "${colors.brightCyan}",
      "brightWhite": "${colors.brightWhite}"
    }
  ],
  "profiles": {
    "defaults": {
      "colorScheme": "${colors.name}"
    }
  }
}`;
}

/**
 * Generate a PowerShell script to apply the skin to Windows Terminal
 */
export function generatePowerShellApplyScript(skin: SkinConfig, schemeName: string): string {
  return `@echo off
REM Retro Skin Application Script for Windows Terminal
REM Generated by Retro Skins Platform
REM Run this script as Administrator

echo Applying "${skin.name}" skin to Windows Terminal...

REM Create backup of original settings.json
if exist "%LOCALAPPDATA%\\Packages\\Microsoft.WindowsTerminal_8wekyb9d8bbwe\\LocalState\\settings.json.bak" (
    echo Backup already exists, skipping...
) else (
    copy "%LOCALAPPDATA%\\Packages\\Microsoft.WindowsTerminal_8wekyb9d8bbwe\\LocalState\\settings.json" "%LOCALAPPDATA%\\Packages\\Microsoft.WindowsTerminal_8wekyb9d8bbwe\\LocalState\\settings.json.bak"
    echo Backup created at settings.json.bak
)

REM The color scheme has been added. To apply:
REM 1. Open Windows Terminal Settings (Ctrl+,)
REM 2. Go to Profiles > Defaults
REM 3. Select Color scheme: "${schemeName}"
REM 4. Or set "colorScheme": "${schemeName}" in your profile

echo.
echo Skin "${skin.name}" configuration generated!
echo Apply it in Windows Terminal Settings > Profiles > Color scheme
`;
}

/**
 * Windows Terminal Adapter class
 */
export class WindowsTerminalAdapter {
  private config: WindowsTerminalConfig;
  private currentSkin: SkinConfig | null = null;
  
  constructor(config: Partial<WindowsTerminalConfig> = {}) {
    this.config = {
      configPath: config.configPath || '%LOCALAPPDATA%/Packages/Microsoft.WindowsTerminal_8wekyb9d8bbwe/LocalState/settings.json',
      backupEnabled: config.backupEnabled ?? true,
    };
  }
  
  /** Apply a skin to Windows Terminal */
  applySkin(skin: SkinConfig): void {
    this.currentSkin = skin;
    const jsonConfig = generateWindowsTerminalJson(skin, this.config);
    
    // Save config
    this.saveConfig(jsonConfig);
  }
  
  /** Get current skin */
  getCurrentSkin(): SkinConfig | null {
    return this.currentSkin;
  }
  
  /** Generate configuration file path */
  getConfigPath(): string {
    return this.config.configPath;
  }
  
  /** Save configuration to file */
  private saveConfig(jsonContent: string): void {
    console.log(`Would save to: ${this.getConfigPath()}`);
    console.log('Config generated successfully');
  }
  
  /** List available skins */
  listSkins(): string[] {
    return [
      'phosphor',
      'amber',
      'lcd',
      'cyber',
      'terminal',
      'puncore',
    ];
  }
  
  /** Switch to a preset skin */
  applyPresetSkin(presetName: string): boolean {
    const skin = this.createPresetSkin(presetName);
    if (skin) {
      this.applySkin(skin);
      return true;
    }
    return false;
  }
  
  /** Create a preset skin by name */
  private createPresetSkin(presetName: string): SkinConfig | null {
    const presets: Record<string, () => SkinConfig> = {
      phosphor: () => ({
        name: 'Phosphor CRT',
        effects: [
          { type: 'crt-scanlines', intensity: 0.4, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.6, params: { radius: 3, falloff: 0.5 } },
        ],
        colors: {
          background: '#0D0208',
          foreground: '#00FF41',
          accent: '#008F11',
          glow: '#00FF41',
          palette: {
            black: '#0D0208',
            red: '#FF3333',
            green: '#00FF41',
            yellow: '#CCFF00',
            blue: '#008F11',
            purple: '#FF00FF',
            cyan: '#00FFFF',
            white: '#00FF41',
            brightBlack: '#1A1A1A',
            brightRed: '#FF6666',
            brightGreen: '#66FF66',
            brightYellow: '#FFFF66',
            brightBlue: '#66FF66',
            brightPurple: '#FF66FF',
            brightCyan: '#66FFFF',
            brightWhite: '#66FF66',
          },
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
      amber: () => ({
        name: 'Amber Monochrome',
        effects: [
          { type: 'crt-scanlines', intensity: 0.3, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.5, params: { radius: 2, falloff: 0.6 } },
        ],
        colors: {
          background: '#1A0F00',
          foreground: '#FFB000',
          accent: '#FF8C00',
          glow: '#FFC000',
          palette: {
            black: '#1A0F00',
            red: '#FF6600',
            green: '#FFB000',
            yellow: '#FFCC00',
            blue: '#994400',
            purple: '#FF8800',
            cyan: '#FFAA00',
            white: '#FFB000',
            brightBlack: '#332200',
            brightRed: '#FF8800',
            brightGreen: '#FFCD00',
            brightYellow: '#FFDD66',
            brightBlue: '#AA6600',
            brightPurple: '#FF9900',
            brightCyan: '#FFDD88',
            brightWhite: '#FFEE99',
          },
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
      lcd: () => ({
        name: 'LCD Display',
        effects: [
          { type: 'crt-scanlines', intensity: 0.1, params: { lineSpacing: 1 } },
        ],
        colors: {
          background: '#0A0A0A',
          foreground: '#E8E8E8',
          accent: '#0077CC',
          glow: '#00DDAA',
          palette: {
            black: '#0A0A0A',
            red: '#FF4444',
            green: '#44FF44',
            yellow: '#FFFF44',
            blue: '#4444FF',
            purple: '#FF44FF',
            cyan: '#44FFFF',
            white: '#E8E8E8',
            brightBlack: '#333333',
            brightRed: '#FF8888',
            brightGreen: '#88FF88',
            brightYellow: '#FFFF88',
            brightBlue: '#8888FF',
            brightPurple: '#FF88FF',
            brightCyan: '#88FFFF',
            brightWhite: '#FFFFFF',
          },
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
      cyber: () => ({
        name: 'Cyber Purple',
        effects: [
          { type: 'crt-scanlines', intensity: 0.35, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.55, params: { radius: 2.5, falloff: 0.5 } },
        ],
        colors: {
          background: '#0D0D1A',
          foreground: '#B388FF',
          accent: '#7C4DFF',
          glow: '#B388FF',
          palette: {
            black: '#0D0D1A',
            red: '#FF0055',
            green: '#00FF66',
            yellow: '#FFFF00',
            blue: '#0085FF',
            purple: '#B388FF',
            cyan: '#00FFFF',
            white: '#E0E0FF',
            brightBlack: '#2A2A3A',
            brightRed: '#FF4488',
            brightGreen: '#66FF99',
            brightYellow: '#FFFF66',
            brightBlue: '#6699FF',
            brightPurple: '#D199FF',
            brightCyan: '#99FFFF',
            brightWhite: '#FFFFFF',
          },
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
      terminal: () => ({
        name: 'Classic Terminal',
        effects: [
          { type: 'crt-scanlines', intensity: 0.25, params: { lineSpacing: 2 } },
        ],
        colors: {
          background: '#0C0C14',
          foreground: '#4AF626',
          accent: '#00AA00',
          glow: '#00FF00',
          palette: {
            black: '#0C0C14',
            red: '#CC3333',
            green: '#4AF626',
            yellow: '#CCFF00',
            blue: '#0066CC',
            purple: '#FF00FF',
            cyan: '#00CCFF',
            white: '#4AF626',
            brightBlack: '#1A1A2A',
            brightRed: '#FF6666',
            brightGreen: '#88FF88',
            brightYellow: '#FFFF66',
            brightBlue: '#6699FF',
            brightPurple: '#FF66FF',
            brightCyan: '#66FFFF',
            brightWhite: '#99FF99',
          },
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
      puncore: () => ({
        name: 'Puncore Neon',
        effects: [
          { type: 'crt-scanlines', intensity: 0.1, params: { lineSpacing: 1 } },
          { type: 'phosphor-glow', intensity: 0.5, params: { radius: 3, falloff: 0.4 } },
        ],
        colors: {
          background: '#575757',
          foreground: '#858585',
          accent: '#FF5700',
          glow: '#8500FF',
          palette: {
            black: '#575757',
            red: '#FF0085',
            green: '#00FF00',
            yellow: '#FF5700',
            blue: '#0085FF',
            purple: '#8500FF',
            cyan: '#0085FF',
            white: '#858585',
            brightBlack: '#313131',
            brightRed: '#FF0085',
            brightGreen: '#00FF00',
            brightYellow: '#FF8500',
            brightBlue: '#0085FF',
            brightPurple: '#8500FF',
            brightCyan: '#00FFFF',
            brightWhite: '#FFFFFF',
          },
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
    };
    
    return presets[presetName]?.() || null;
  }
}

/**
 * Create a Windows Terminal adapter instance
 */
export function createWindowsTerminalAdapter(config?: Partial<WindowsTerminalConfig>): WindowsTerminalAdapter {
  return new WindowsTerminalAdapter(config);
}
