/**
 * WezTerm Adapter
 * 
 * Integrates retro skins with WezTerm terminal emulator.
 * WezTerm supports Lua scripting for customization.
 */

import type { SkinConfig } from '../../skins.js';

// Define WezTermColors type locally since it's not exported
type WezTermColors = {
  ansi: string[];
  brights: string[];
};

export interface WezTermConfig {
  /** WezTerm configuration directory */
  configDir: string;
  /** Whether to enable animations */
  enableAnimations: boolean;
  /** Animation FPS */
  animationFps: number;
}

export interface WezTermSkinData {
  name: string;
  colors: WezTermColors;
  foreground: string;
  background: string;
  cursor_bg: string;
  cursor_fg: string;
  selection_bg: string;
  selection_fg: string;
}

/**
 * Convert our skin config to WezTerm format
 */
export function toWezTermColors(skin: SkinConfig): WezTermSkinData {
  const p = skin.colors.palette;

  // Use palette if available, otherwise use defaults
  const weztermColors: WezTermColors = {
    ansi: p
      ? [p.black, p.red, p.green, p.yellow, p.blue, p.purple, p.cyan, p.white]
      : [
          skin.colors.background, // black
          '#FF0000', // red
          '#00FF00', // green
          '#FFFF00', // yellow
          '#0000FF', // blue
          '#FF00FF', // magenta
          '#00FFFF', // cyan
          skin.colors.foreground, // white
        ],
    brights: p
      ? [p.brightBlack, p.brightRed, p.brightGreen, p.brightYellow, p.brightBlue, p.brightPurple, p.brightCyan, p.brightWhite]
      : [
          '#404040',
          '#FF6666',
          '#66FF66',
          '#FFFF66',
          '#6666FF',
          '#FF66FF',
          '#66FFFF',
          '#FFFFFF',
        ],
  };
  
  return {
    name: skin.name,
    colors: weztermColors,
    foreground: skin.colors.foreground,
    background: skin.colors.background,
    cursor_bg: skin.colors.accent,
    cursor_fg: skin.colors.background,
    selection_bg: skin.colors.accent,
    selection_fg: skin.colors.foreground,
  };
}

/**
 * Generate WezTerm Lua configuration for a skin
 */
export function generateWezTermLua(skin: SkinConfig, options: Partial<WezTermConfig> = {}): string {
  const wezColors = toWezTermColors(skin);
  const config = {
    configDir: options.configDir || '~/.config/wezterm',
    enableAnimations: options.enableAnimations ?? true,
    animationFps: options.animationFps || 60,
  };

  return `-- Retro Skin: ${skin.name}
-- Generated by Retro Skins Platform

local wezterm = require 'wezterm'

-- Color scheme
local colors = {
  ansi = { ${wezColors.colors.ansi.map(c => `'${c}'`).join(', ')} },
  brights = { ${wezColors.colors.brights.map(c => `'${c}'`).join(', ')} },
  foreground = '${wezColors.foreground}',
  background = '${wezColors.background}',
  cursor_bg = '${wezColors.cursor_bg}',
  cursor_fg = '${wezColors.cursor_fg}',
  selection_bg = '${wezColors.selection_bg}',
  selection_fg = '${wezColors.selection_fg}',
  
  -- Retro glow effect colors
  tab_bar = {
    background = '${skin.colors.background}',
    active_tab = {
      bg_color = '${skin.colors.accent}',
      fg_color = '${skin.colors.foreground}',
    },
    inactive_tab = {
      bg_color = '${skin.colors.background}',
      fg_color = '${skin.colors.foreground}',
    },
  },
  
  -- Scrollbar styling
  scrollbar_thumb = '${skin.colors.accent}',
}

-- Apply colors
wezterm.on('configure-colors', function(window, pane)
  window:set_config_colors(colors)
end)

-- Phosphor glow effect (using text shadows)
wezterm.on('format-window-title', function(tab, tabs, panes, config)
  return {
    { Text = ' ' .. tab.tab_title .. ' ' },
  }
end)

-- Enable animations if supported
if ${config.enableAnimations} then
  wezterm.on('update-status', function(window, pane)
    -- Animation hooks for future animated backgrounds
  end)
end

-- Key bindings for skin switching
wezterm.on('keybinding-event', function(window, pane, event)
  if event.key == 'F12' then
    -- Toggle between skins
  end
end)

-- Performance settings
config.animation_fps = ${config.animationFps}
config.enable_tab_bar = true
config.use_fancy_tab_bar = true

return config
`;
}

/**
 * WezTerm Adapter class
 */
export class WezTermAdapter {
  private config: WezTermConfig;
  private currentSkin: SkinConfig | null = null;
  
  constructor(config: Partial<WezTermConfig> = {}) {
    this.config = {
      configDir: config.configDir || '~/.config/wezterm',
      enableAnimations: config.enableAnimations ?? true,
      animationFps: config.animationFps || 60,
    };
  }
  
  /** Apply a skin to WezTerm */
  applySkin(skin: SkinConfig): void {
    this.currentSkin = skin;
    const luaConfig = generateWezTermLua(skin, this.config);
    
    // Save to WezTerm config file
    this.saveConfig(luaConfig);
  }
  
  /** Get current skin */
  getCurrentSkin(): SkinConfig | null {
    return this.currentSkin;
  }
  
  /** Generate configuration file path */
  private getConfigPath(): string {
    return `${this.config.configDir}/retro_skin.lua`;
  }
  
  /** Save configuration to file */
  private saveConfig(luaContent: string): void {
    // This would write to the WezTerm config directory
    // In a real implementation, this would use fs.writeFile
    console.log(`Would save to: ${this.getConfigPath()}`);
    console.log('Config generated successfully');
  }
  
  /** List available skins */
  listSkins(): string[] {
    return [
      'phosphor',
      'amber',
      'lcd',
      'cyber',
      'terminal',
    ];
  }
  
  /** Switch to a preset skin */
  applyPresetSkin(presetName: string): boolean {
    const skin = this.createPresetSkin(presetName);
    if (skin) {
      this.applySkin(skin);
      return true;
    }
    return false;
  }
  
  /** Create a preset skin by name */
  private createPresetSkin(presetName: string): SkinConfig | null {
    const presets: Record<string, () => SkinConfig> = {
      phosphor: () => ({
        name: 'Phosphor CRT',
        effects: [
          { type: 'crt-scanlines', intensity: 0.4, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.6, params: { radius: 3, falloff: 0.5 } },
        ],
        colors: {
          background: '#0D0208',
          foreground: '#00FF41',
          accent: '#008F11',
          glow: '#00FF41',
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
      amber: () => ({
        name: 'Amber Monochrome',
        effects: [
          { type: 'crt-scanlines', intensity: 0.3, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.5, params: { radius: 2, falloff: 0.6 } },
        ],
        colors: {
          background: '#1A0F00',
          foreground: '#FFB000',
          accent: '#FF8C00',
          glow: '#FFB000',
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
    };
    
    return presets[presetName]?.() || null;
  }
}

/**
 * Create a WezTerm adapter instance
 */
export function createWezTermAdapter(config?: Partial<WezTermConfig>): WezTermAdapter {
  return new WezTermAdapter(config);
}
