/**
 * Alacritty Adapter
 * 
 * Integrates retro skins with Alacritty terminal emulator.
 * Alacritty uses YAML configuration files with color sections.
 */

import type { SkinConfig } from '../../skins.js';

export interface AlacrittyConfig {
  /** Alacritty configuration directory */
  configDir: string;
  /** Whether to enable live config reload */
  liveConfigReload: boolean;
}

export interface AlacrittyColors {
  primary: {
    background: string;
    foreground: string;
    bright_foreground?: string;
    dim_foreground?: string;
  };
  cursor?: {
    cursor: string;
    text?: string;
  };
  vi_mode_cursor?: {
    cursor: string;
    text?: string;
  };
  search?: {
    cursor: string;
    text: string;
  };
  line_indicator?: {
    foreground?: string;
    background?: string;
  };
  selection?: {
    text: string;
    background: string;
  };
  normal?: {
    black: string;
    red: string;
    green: string;
    yellow: string;
    blue: string;
    magenta: string;
    cyan: string;
    white: string;
  };
  bright?: {
    black: string;
    red: string;
    green: string;
    yellow: string;
    blue: string;
    magenta: string;
    cyan: string;
    white: string;
  };
  dim?: {
    black: string;
    red: string;
    green: string;
    yellow: string;
    blue: string;
    magenta: string;
    cyan: string;
    white: string;
  };
}

/**
 * Convert our skin config to Alacritty format
 */
export function toAlacrittyColors(skin: SkinConfig): AlacrittyColors {
  const p = skin.colors.palette;

  return {
    primary: {
      background: skin.colors.background,
      foreground: skin.colors.foreground,
    },
    cursor: {
      cursor: skin.colors.accent,
      text: skin.colors.background,
    },
    selection: {
      background: skin.colors.accent,
      text: skin.colors.foreground,
    },
    normal: p
      ? {
          black: p.black,
          red: p.red,
          green: p.green,
          yellow: p.yellow,
          blue: p.blue,
          magenta: p.purple,
          cyan: p.cyan,
          white: p.white,
        }
      : {
          black: skin.colors.background,
          red: '#FF0000',
          green: '#00FF00',
          yellow: '#FFFF00',
          blue: '#0000FF',
          magenta: '#FF00FF',
          cyan: '#00FFFF',
          white: skin.colors.foreground,
        },
    bright: p
      ? {
          black: p.brightBlack,
          red: p.brightRed,
          green: p.brightGreen,
          yellow: p.brightYellow,
          blue: p.brightBlue,
          magenta: p.brightPurple,
          cyan: p.brightCyan,
          white: p.brightWhite,
        }
      : {
          black: '#404040',
          red: '#FF6666',
          green: '#66FF66',
          yellow: '#FFFF66',
          blue: '#6666FF',
          magenta: '#FF66FF',
          cyan: '#66FFFF',
          white: '#FFFFFF',
        },
  };
}

/**
 * Generate Alacritty YAML configuration for a skin
 */
export function generateAlacrittyYaml(skin: SkinConfig, options: Partial<AlacrittyConfig> = {}): string {
  const colors = toAlacrittyColors(skin);
  const config = {
    configDir: options.configDir || '~/.config/alacritty',
    liveConfigReload: options.liveConfigReload ?? true,
  };

  return `# Retro Skin: ${skin.name}
# Generated by Retro Skins Platform

colors:
  # Primary colors
  primary:
    background: '${colors.primary.background}'
    foreground: '${colors.primary.foreground}'
    
  # Cursor styling
  cursor:
    cursor: '${colors.cursor?.cursor}'
    text: '${colors.cursor?.text}'
    
  # Selection styling
  selection:
    text: '${colors.selection?.text}'
    background: '${colors.selection?.background}'
    
  # ANSI color palette
  normal:
    black: '${colors.normal?.black ?? ""}'
    red: '${colors.normal?.red ?? ""}'
    green: '${colors.normal?.green ?? ""}'
    yellow: '${colors.normal?.yellow ?? ""}'
    blue: '${colors.normal?.blue ?? ""}'
    magenta: '${colors.normal?.magenta ?? ""}'
    cyan: '${colors.normal?.cyan ?? ""}'
    white: '${colors.normal?.white ?? ""}'
    
  # Bright ANSI colors
  bright:
    black: '${colors.bright?.black ?? ""}'
    red: '${colors.bright?.red ?? ""}'
    green: '${colors.bright?.green ?? ""}'
    yellow: '${colors.bright?.yellow ?? ""}'
    blue: '${colors.bright?.blue ?? ""}'
    magenta: '${colors.bright?.magenta ?? ""}'
    cyan: '${colors.bright?.cyan ?? ""}'
    white: '${colors.bright?.white ?? ""}'

# Visual effects (Alacritty supports some built-in effects)
# Note: Advanced CRT effects require external compositor

# Window decoration
window:
  decorations: "Full"
  opacity: 1.0

# Cursor configuration
cursor:
  style: "Block"
  blink: "On"

# Performance settings
live_config_reload: ${config.liveConfigReload}
`;
}

/**
 * Alacritty Adapter class
 */
export class AlacrittyAdapter {
  private config: AlacrittyConfig;
  private currentSkin: SkinConfig | null = null;
  
  constructor(config: Partial<AlacrittyConfig> = {}) {
    this.config = {
      configDir: config.configDir || '~/.config/alacritty',
      liveConfigReload: config.liveConfigReload ?? true,
    };
  }
  
  /** Apply a skin to Alacritty */
  applySkin(skin: SkinConfig): void {
    this.currentSkin = skin;
    const yamlConfig = generateAlacrittyYaml(skin, this.config);
    
    // Save to Alacritty config file
    this.saveConfig(yamlConfig);
  }
  
  /** Get current skin */
  getCurrentSkin(): SkinConfig | null {
    return this.currentSkin;
  }
  
  /** Generate configuration file path */
  private getConfigPath(): string {
    return `${this.config.configDir}/alacritty.yml`;
  }
  
  /** Save configuration to file */
  private saveConfig(yamlContent: string): void {
    // This would write to the Alacritty config directory
    // In a real implementation, this would use fs.writeFile
    console.log(`Would save to: ${this.getConfigPath()}`);
    console.log('Config generated successfully');
  }
  
  /** List available skins */
  listSkins(): string[] {
    return [
      'phosphor',
      'amber',
      'lcd',
      'cyber',
      'terminal',
    ];
  }
  
  /** Switch to a preset skin */
  applyPresetSkin(presetName: string): boolean {
    const skin = this.createPresetSkin(presetName);
    if (skin) {
      this.applySkin(skin);
      return true;
    }
    return false;
  }
  
  /** Create a preset skin by name */
  private createPresetSkin(presetName: string): SkinConfig | null {
    const presets: Record<string, () => SkinConfig> = {
      phosphor: () => ({
        name: 'Phosphor CRT',
        effects: [
          { type: 'crt-scanlines', intensity: 0.4, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.6, params: { radius: 3, falloff: 0.5 } },
        ],
        colors: {
          background: '#0D0208',
          foreground: '#00FF41',
          accent: '#008F11',
          glow: '#00FF41',
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
      amber: () => ({
        name: 'Amber Monochrome',
        effects: [
          { type: 'crt-scanlines', intensity: 0.3, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.5, params: { radius: 2, falloff: 0.6 } },
        ],
        colors: {
          background: '#1A0F00',
          foreground: '#FFB000',
          accent: '#FF8C00',
          glow: '#FFB000',
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
    };
    
    return presets[presetName]?.() || null;
  }
}

/**
 * Create an Alacritty adapter instance
 */
export function createAlacrittyAdapter(config?: Partial<AlacrittyConfig>): AlacrittyAdapter {
  return new AlacrittyAdapter(config);
}
