/**
 * Kitty Adapter
 * 
 * Integrates retro skins with Kitty terminal emulator.
 * Kitty uses a plain text configuration file with key=value pairs.
 */

import type { SkinConfig } from '../../skins.js';

export interface KittyConfig {
  /** Kitty configuration directory */
  configDir: string;
  /** Whether to enable live reload */
  liveConfigReload: boolean;
}

export interface KittyColors {
  foreground: string;
  background: string;
  selection_foreground: string;
  selection_background: string;
  cursor: string;
  cursor_text_color: string;
  ansi: string[];
}

/**
 * Convert our skin config to Kitty format
 */
export function toKittyColors(skin: SkinConfig): KittyColors {
  const p = skin.colors.palette;

  return {
    foreground: skin.colors.foreground,
    background: skin.colors.background,
    selection_foreground: skin.colors.foreground,
    selection_background: skin.colors.accent,
    cursor: skin.colors.accent,
    cursor_text_color: skin.colors.background,
    ansi: p
      ? [p.black, p.red, p.green, p.yellow, p.blue, p.purple, p.cyan, p.white]
      : [
          skin.colors.background, // black
          '#FF0000', // red
          '#00FF00', // green
          '#FFFF00', // yellow
          '#0000FF', // blue
          '#FF00FF', // magenta
          '#00FFFF', // cyan
          skin.colors.foreground, // white
        ],
  };
}

/**
 * Generate Kitty configuration for a skin
 */
export function generateKittyConfig(skin: SkinConfig, options: Partial<KittyConfig> = {}): string {
  const colors = toKittyColors(skin);
  const config = {
    configDir: options.configDir || '~/.config/kitty',
    liveConfigReload: options.liveConfigReload ?? true,
  };

  return `# Retro Skin: ${skin.name}
# Generated by Retro Skins Platform

# Basic colors
foreground ${colors.foreground}
background ${colors.background}

# Selection colors
selection_foreground ${colors.selection_foreground}
selection_background ${colors.selection_background}

# Cursor styling
cursor ${colors.cursor}
cursor_text_color ${colors.cursor_text_color}

# ANSI color palette
# Black
color0 ${colors.ansi[0]}
# Red
color1 ${colors.ansi[1]}
# Green
color2 ${colors.ansi[2]}
# Yellow
color3 ${colors.ansi[3]}
# Blue
color4 ${colors.ansi[4]}
# Magenta
color5 ${colors.ansi[5]}
# Cyan
color6 ${colors.ansi[6]}
# White
color7 ${colors.ansi[7]}

# Bright ANSI colors
color8 #404040
color9 #FF6666
color10 #66FF66
color11 #FFFF66
color12 #6666FF
color13 #FF66FF
color14 #66FFFF
color15 #FFFFFF

# Window settings
window_padding_width 2
hide_window_decorations no

# Cursor settings
cursor_shape block
cursor_blink interval

# Visual effects (Kitty supports some advanced effects)
# Note: CRT effects require external compositor like picom

# Performance
repaint_delay 10
input_delay 3

# Tab bar
tab_bar_style fade
tab_fade 0.5

# Font settings (adjust for your system)
# font_family JetBrainsMono Nerd Font
# font_size 12
`;
}

/**
 * Kitty Adapter class
 */
export class KittyAdapter {
  private config: KittyConfig;
  private currentSkin: SkinConfig | null = null;
  
  constructor(config: Partial<KittyConfig> = {}) {
    this.config = {
      configDir: config.configDir || '~/.config/kitty',
      liveConfigReload: config.liveConfigReload ?? true,
    };
  }
  
  /** Apply a skin to Kitty */
  applySkin(skin: SkinConfig): void {
    this.currentSkin = skin;
    const configContent = generateKittyConfig(skin, this.config);
    
    // Save to Kitty config file
    this.saveConfig(configContent);
  }
  
  /** Get current skin */
  getCurrentSkin(): SkinConfig | null {
    return this.currentSkin;
  }
  
  /** Generate configuration file path */
  private getConfigPath(): string {
    return `${this.config.configDir}/retro_skin.conf`;
  }
  
  /** Save configuration to file */
  private saveConfig(configContent: string): void {
    // This would write to the Kitty config directory
    // In a real implementation, this would use fs.writeFile
    console.log(`Would save to: ${this.getConfigPath()}`);
    console.log('Config generated successfully');
  }
  
  /** List available skins */
  listSkins(): string[] {
    return [
      'phosphor',
      'amber',
      'lcd',
      'cyber',
      'terminal',
    ];
  }
  
  /** Switch to a preset skin */
  applyPresetSkin(presetName: string): boolean {
    const skin = this.createPresetSkin(presetName);
    if (skin) {
      this.applySkin(skin);
      return true;
    }
    return false;
  }
  
  /** Create a preset skin by name */
  private createPresetSkin(presetName: string): SkinConfig | null {
    const presets: Record<string, () => SkinConfig> = {
      phosphor: () => ({
        name: 'Phosphor CRT',
        effects: [
          { type: 'crt-scanlines', intensity: 0.4, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.6, params: { radius: 3, falloff: 0.5 } },
        ],
        colors: {
          background: '#0D0208',
          foreground: '#00FF41',
          accent: '#008F11',
          glow: '#00FF41',
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
      amber: () => ({
        name: 'Amber Monochrome',
        effects: [
          { type: 'crt-scanlines', intensity: 0.3, params: { lineSpacing: 2 } },
          { type: 'phosphor-glow', intensity: 0.5, params: { radius: 2, falloff: 0.6 } },
        ],
        colors: {
          background: '#1A0F00',
          foreground: '#FFB000',
          accent: '#FF8C00',
          glow: '#FFB000',
        },
        performance: { gpuAcceleration: true, targetFps: 60, quality: 'high' },
      }),
    };
    
    return presets[presetName]?.() || null;
  }
}

/**
 * Create a Kitty adapter instance
 */
export function createKittyAdapter(config?: Partial<KittyConfig>): KittyAdapter {
  return new KittyAdapter(config);
}
